@startuml
start
  :以下のように配列を代入する

  16  16  0   0   0   0   16  16
                                  
  16  0   0   0   0   0   0   16
                                
  0   0   0   8   4   0   0   0
                              
  0   0   8   1   2   4   0   0 
                              
  0   0   4   2   1   8   0   0 
                              
  0   0   0   4   8   0   0   0 
                             
  16  0   0   0   0   0   0   16
                         
  16  16  0   0   0   0   16  16
  *sqStatus[0][0]に何が代入されているかによって意味が変わる.;
  :黒石をターンに設定;
  :tesuuに0を代入;
  :winerに3を代入;
  :initPlayerを実行して構造体内のgamePlayerを初期化する;
  :initStoneを実行して構造体内のStoneを初期化する;
  :画面表示;

@enduml