@startuml inputStonePosition
start
if(入力コマンドが<なら)then (yes)
    if(手数が0以下なら)then (yes)
        :"これ以上戻れません"と表示;
        :1を返す準備;
    else (手数が0以上なら) 
        :"一つ前の配置に戻します";
        :0を返す準備;
    endif
elseif(入力コマンドが>なら)then (yes)
    if(これ以上先の手がないなら)then (yes)
        :"これ以上先にいけません"と表示;
        :1を返す準備;
    else (手数が0以上なら) 
        :"一つ先の配置に進みます";
        :0を返す準備;
    endif
else (アルファベットなら)
    :盤上の配置可能な場所の数を取得;
    if(入力されたアルファベットが配置可能な場所に該当すれば)then (yes)
        :flagに1を代入;
    endif
    if(flagが1なら)then (yes)
        :現在の手数以降のbkpboardの情報を初期化;
        :0を返す準備;
    else (そうでなければ)
        :"そのような置き場所はありません。
        もしくはコマンドは存在しません"と表示;
        :1を返す準備;
    endif
endif
:準備した返り値を返す;
stop
@enduml