@startuml
start
:円周上の座標を時計回りに配列に格納する;
if(指定された座標が盤の端に存在するか)then (yes)
    if(黒のターンなら)then (yes)
        :敵石を白に設定;
        :自分の石を黒に設定;
    endif
    if(白のターンなら)then (yes)
        :敵石を黒に設定;
        :自分の石を白に設定;
    endif
    :入力された座標から、判定処理の開始位置を決定する
    盤の端のマスに割り当てたplace(0-19)の番号と現在の座標を照合;
    while (20回ループ)
        :paleces関数をインクリーメントして盤の端を回る;
        if(placesが20なら)then (yes)
            :次はplacesが0の場所に飛ぶ;
        endif
        if(plaxesが19番目の場所なら)then (yes)
            if(19番目の場所が敵石で0番目の場所が自分の石なら)then (yes)
                :返り値を1にする準備;
                :forを抜ける;
            else(そうれなければ)
                :0を返す準備;
            endif
        else (それ以外の場所なら)
            if(placesで指定した場所が敵石で、その次の石が見方の石なら)then (yes)
                :返り値を1にする準備;
                :ループを抜ける;
            else (そうでなければ)
                :返り値を0にする準備;
            endif
        endif
    endwhile
else (指定した座標が盤の端にない)
    :0を返す準備;
endif
:準備した返り値を返す;
stop
@enduml